<?php
declare(strict_types=1);

/** Records the download, then streams the package (or redirects to a real URL if one is set). */
$page_layout = false;

$asset = asset_by_id((int)($params['id'] ?? 0));
if ($asset === null) {
    http_response_code(404);
    page_layout('', 'Page not found', render_fragment(__DIR__ . '/not_found.php', ['requested' => '/download/' . (string)($params['id'] ?? '')]));
    return;
}

$user = current_user();

if ((bool)$asset['is_premium']) {
    if ($user === null) {
        flash('Sign in to download premium files.', 'warning');
        redirect('/login');
    }
    if (!has_unlocked((int)$user['id'], (int)$asset['id'])) {
        flash('That file is locked — unlock it with crypto first.', 'warning');
        redirect('/asset/' . $asset['slug']);
    }
}

record_download((int)$asset['id'], $user === null ? null : (int)$user['id'], (string)($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0'));

if (!empty($asset['download_url'])) {
    header('Location: ' . $asset['download_url']);
    exit;
}

// No external file attached yet: hand out a readable placeholder package so the flow is complete.
$lines = [
    (string)$asset['name'],
    str_repeat('=', strlen((string)$asset['name'])),
    '',
    'Author:             ' . $asset['author'],
    'Minecraft version:  ' . $asset['mc_version'],
    'Category:           ' . category_label($asset['category']),
    'PC impact:          ' . impact_label($asset['impact']),
    'Licence:            ' . ((bool)$asset['is_premium'] ? 'Premium unlock' : 'Free / community'),
    '',
    'What is included',
    '----------------',
];
foreach (includes_list($asset) as $line) {
    $lines[] = ' - ' . $line;
}
$lines[] = '';
$lines[] = 'Notes';
$lines[] = '-----';
$lines[] = (string)$asset['description'];
$lines[] = '';
$lines[] = 'This is a placeholder package generated by the demo catalogue. The hub owner can attach a real';
$lines[] = 'file or CDN link to this item from the admin panel, and buyers will then receive that file instead.';

$body = implode("\n", $lines);

header('Content-Type: text/plain; charset=utf-8');
header('Content-Disposition: attachment; filename="' . str_replace('"', '', (string)$asset['file_name']) . '"');
header('Content-Length: ' . strlen($body));
echo $body;
